### ISSUE TITLE
Found a minor typo in the Strings section

### ISSUE THREAD

**Issue by userhiren** [in28minutes/JavaInterviewQuestionsAndAnswers#3]
The comment next to the code line shows the value `cdefghij` but should be `defghij`

https://github.com/in28minutes/JavaInterviewQuestionsAndAnswers/blob/master/src/main/java/com/in28minutes/java/string/StringExamples.java#L58

**Comment by in28minutes** [comment]
Thanks Hiren. Fixed Now.
