### ISSUE TITLE
Pdf 

### ISSUE THREAD

**Issue by nikesh999** [in28minutes/JavaInterviewQuestionsAndAnswers#7]
I can't find the pdf for the course in the resources. is there any other way finding the pdf?

**Comment by in28minutes** [comment]
Which platform are you referring to?

**Comment by kmne68** [comment]
I also cannot find the Resources section or PDF Guide. I am using the StackSkills version of the course:
https://stackskills.com/courses/146461/lectures/2170946

**Comment by shahid938** [comment]
Hi I'm going through the Java interview questions course in Safari , I'm trying to access the Java interview questions PDF but not able to find the link .

**Comment by in28minutes** [comment]
Please download it from here - https://github.com/in28minutes/JavaInterviewQuestionsAndAnswers/blob/master/JavaInterviewQuestions-UdemyCourse.pdf
